### ISSUE TITLE
Never ending installing dependencies

### ISSUE THREAD

**Issue by jeroenouw** [liftr-framework/cli#1]
If I run `liftr -s` without a name specified, it gives an error but not a specific one and the following sentence keeps loading:
`Creating necessary files and installing dependencies. This may take a while...`

```⠋ Setting up Scaffold project(node:42932) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type boolean
    at Object.mkdirSync (fs.js:767:3)
    at Object.<anonymous> (/Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/create/createSetup.js:73:57)
    at step (/Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/create/createSetup.js:32:23)
    at Object.next (/Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/create/createSetup.js:13:53)
    at /Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/create/createSetup.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/create/createSetup.js:3:12)
    at Object.exports.createSetup (/Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/create/createSetup.js:50:53)
    at Object.<anonymous> (/Users/jeroenouw/Documents/githubprojecten/cli/liftr/lib/index.js:30:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
(node:42932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
🌏  Creating necessary files and installing dependencies. This may take a while...
```

**Comment by farisT** [comment]
This bug is fixed with v1.2 https://github.com/farisT/liftr/releases/tag/v1.2 :thumbsup:
