### ISSUE TITLE
After build Node can't find @routes

### ISSUE THREAD

**Issue by devbyray** [liftr-framework/cli#18]
I'm getting this error. It is because Typescript knows about this route, but Node doesn't know. This package is maybe the solution https://github.com/ilearnio/module-alias

```
Error: Cannot find module '@routes/LiftrRoutingModule'
grip_1  | Require stack:
grip_1  | - /home/node/dist/server.js
grip_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
grip_1  |     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
grip_1  |     at Module.require (internal/modules/cjs/loader.js:1040:19)
grip_1  |     at require (internal/modules/cjs/helpers.js:72:18)
grip_1  |     at Object.<anonymous> (/home/node/dist/server.js:17:30)
grip_1  |     at Module._compile (internal/modules/cjs/loader.js:1151:30)
grip_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
grip_1  |     at Module.load (internal/modules/cjs/loader.js:1000:32)
grip_1  |     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
grip_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
grip_1  |   code: 'MODULE_NOT_FOUND',
grip_1  |   requireStack: [ '/home/node/dist/server.js' ]
grip_1  | }
grip_1  | internal/modules/cjs/loader.js:983
grip_1  |   throw err;
```

**Comment by farisT** [comment]
the package [tsconfig-paths](https://github.com/dividab/tsconfig-paths) resolves all the routes at run-time. It is included in the Liftr boilerplate. You can run `node -r tsconfig-paths/register server.js` within the dist folder and it should work. Otherwise, npm start will work as well since tsconfig-paths is part iof the nodemon.json config.
